apiVersion: v1
name: proxy
version: 0.1.0
appVersion: 0.1.0
description: Zabbix is a mature and effortless enterprise-class open source monitoring solution for network monitoring and application monitoring of millions of metrics.
keywords:
  - zabbix
  - monitoring
  - metics
home: https://www.zabbix.com/
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png
source:
  - https://github.com/cetic/helm-zabbix
maintainers:
  - name: AyadiAmen
  - name: alexnuttinck