{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zabbix.serviceAccountName" . }}
  labels:
{{ include "zabbix.labels" . | indent 4 }}
{{- end -}}
