---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "zabbix.fullname" . }}
  labels:
    app: zabbix-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  serviceName: {{ template "zabbix.fullname" . }}
  selector:
    matchLabels:
      app:  zabbix-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: zabbix-server
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
        - name: zabbix-server
          image: {{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}
          ports:
            - containerPort: 10051
              name: zabbix-trapper
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10051
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}    
            - containerPort: 10052
              name: zabbix-jmx
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10052              
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}    
          env:
            - name: DB_SERVER_HOST
              value: {{ .Values.zabbixServer.DB_SERVER_HOST }}
            - name: POSTGRES_USER
              value: {{ .Values.zabbixServer.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.zabbixServer.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.zabbixServer.POSTGRES_DB }}
          {{- if .Values.zabbixagent.enabled }}
        - name: zabbix-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.zabbixagent.image.repository }}:{{ .Values.zabbixagent.image.tag }}"
          imagePullPolicy: {{ .Values.zabbixServer.image.pullPolicy }}
          env:
            - name: ZBX_HOSTNAME
              value: {{ .Values.zabbixagent.ZBX_HOSTNAME }}
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbixagent.ZBX_SERVER_HOST | quote }}
            - name: ZBX_SERVER_PORT
              value: {{ .Values.zabbixagent.ZBX_SERVER_PORT | quote }}
            - name: ZBX_PASSIVE_ALLOW
              value: {{ .Values.zabbixagent.ZBX_PASSIVE_ALLOW | quote }}
            - name: ZBX_PASSIVESERVERS
              value: {{ .Values.zabbixagent.ZBX_PASSIVESERVERS | quote }}
            - name: ZBX_ACTIVE_ALLOW
              value: {{ .Values.zabbixagent.ZBX_ACTIVE_ALLOW | quote }}
            - name: ZBX_ACTIVESERVERS
              value: {{ .Values.zabbixagent.ZBX_ACTIVESERVERS | quote }}
            - name: ZBX_DEBUGLEVEL
              value: {{ .Values.zabbixagent.ZBX_DEBUGLEVEL | quote }}
            - name: ZBX_TIMEOUT
              value: {{ .Values.zabbixagent.ZBX_TIMEOUT }}
            - name: ZBX_LOADMODULE
              value: {{ .Values.zabbixagent.ZBX_LOADMODULE }}
          ports:
            - name: zabbix-agent
              containerPort: 10050
              protocol: TCP
          {{- end }}
        {{- if .Values.zabbixproxy.enabled }}
        - name: zabbix-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.zabbixproxy.image.repository }}:{{ .Values.zabbixproxy.image.tag }}"
          imagePullPolicy: {{ .Values.zabbixServer.image.pullPolicy }}
          env:
            - name: ZBX_PROXYMODE
              value: {{ .Values.zabbixproxy.ZBX_PROXYMODE | quote }}
            - name: ZBX_HOSTNAME
              value: {{ .Values.zabbixproxy.ZBX_HOSTNAME | quote }}
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbixproxy.ZBX_SERVER_HOST | quote }}
            - name: ZBX_SERVER_PORT
              value: {{ .Values.zabbixproxy.ZBX_SERVER_PORT | quote }}
            - name: DB_SERVER_HOST
              value: {{ .Values.zabbixproxy.DB_SERVER_HOST | quote }}
            - name: DB_SERVER_PORT
              value: {{ .Values.zabbixproxy.DB_SERVER_PORT | quote }}
            - name: MYSQL_USER
              value: {{ .Values.zabbixproxy.MYSQL_USER }}
            # - name: MYSQL_USER_FILE
            #  value: value: {{ .Values.zabbixproxy.POSTGRES_USER_FILE }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.zabbixproxy.MYSQL_PASSWORD }}
            #- name: MYSQL_PASSWORD_FILE
            #  value: value: {{ .Values.zabbixproxy.MYSQL_PASSWORD_FILE }}
            - name: MYSQL_DATABASE
              value: {{ .Values.zabbixproxy.MYSQL_DATABASE }}
            - name: ZBX_LOADMODULE
              value: {{ .Values.zabbixproxy.ZBX_LOADMODULE }}
            - name: ZBX_DEBUGLEVEL
              value: {{ .Values.zabbixproxy.ZBX_DEBUGLEVEL | quote }}
            - name: ZBX_TIMEOUT
              value: {{ .Values.zabbixproxy.ZBX_TIMEOUT }}
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: {{ .Values.zabbixproxy.ZBX_VMWARECACHESIZE }}
          ports:
            - name: http
              containerPort: 10051
              protocol: TCP
        {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixServer.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- range .Values.zabbixagent.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- if .Values.zabbixproxy.enabled }}
      {{- range .Values.zabbixproxy.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- end }}
