{{- if .Values.zabbixServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
    {{- if .Values.zabbixServer.deploymentLabels }}
    {{- toYaml .Values.zabbixServer.deploymentLabels | nindent 4 }}
    {{- end }}
    {{- if and .Values.zabbixAgent.enabled .Values.zabbixAgent.runAsSidecar }}
      {{- if .Values.zabbixAgent.deploymentLabels }}
        {{- toYaml .Values.zabbixAgent.deploymentLabels | nindent 4 }}
      {{- end }}
    {{- end }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
  replicas: {{ .Values.zabbixServer.replicaCount }}
  strategy:
    type: RollingUpdate
  {{- else }}
  replicas: 1
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "zabbix.fullname" . }}-zabbix-server
  template:
    metadata:
      annotations:
        {{- range $key,$value := .Values.zabbixServer.containerAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
        zabbix.com/server-ha-enabled: "true"
        {{- end }}
        app: {{ template "zabbix.fullname" . }}-zabbix-server
        app.kubernetes.io/name: zabbix-server
        helm.sh/chart: {{ include "zabbix.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
        {{- if .Values.zabbixServer.containerLabels }}
        {{- toYaml .Values.zabbixServer.containerLabels | nindent 8 }}
        {{- end }}
        {{- if and .Values.zabbixAgent.enabled .Values.zabbixAgent.runAsSidecar }}
          {{- if .Values.zabbixAgent.containerLabels }}
            {{- toYaml .Values.zabbixAgent.containerLabels | nindent 8 }}
          {{- end }}
        {{- end }}
    spec:
      {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
      shareProcessNamespace: true
      {{- end }}
      serviceAccountName: {{ template "zabbix.serviceAccountName" . }}
      {{- with .Values.zabbixServer.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.karpenter.enabled }}
      {{- with .Values.karpenter.labels }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixServer.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
        - name: init-wait-for-database-schema
          {{- if .Values.zabbixServer.image.tag }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          env:
            {{- include "zabbix.postgresAccess.variables" (list $ . "zabbix") | nindent 12 }}
            {{- with .Values.zabbixServer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.zabbixServer.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.zabbixServer.resources | nindent 12 }}
          command:
            - "/bin/bash"
            - "/script/wait_db_schema.sh"
          volumeMounts:
            - name: init-waitschema-script
              mountPath: /script
      {{- end }}
      {{- with .Values.zabbixServer.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zabbix-server
          resources:
            {{- toYaml .Values.zabbixServer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.zabbixServer.securityContext | nindent 12 }}
          {{- if .Values.zabbixServer.image.tag }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zabbixServer.image.pullPolicy }}
          ports:
            - containerPort: 10051
              name: zabbix-server
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10051
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}
            - containerPort: 10052
              name: zabbix-jmx
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10052
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}
          env:
            {{- include "zabbix.postgresAccess.variables" (list $ . "zabbix") | nindent 12 }}
            {{- with .Values.zabbixServer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
            - name: ZBX_AUTOHANODENAME
              value: "hostname"
            - name: ZBX_NODEADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- end }}
            {{- if .Values.zabbixWebService.enabled }}
            - name: ZBX_WEBSERVICEURL
              value: "http://{{ template "zabbix.fullname" . }}-zabbix-webservice:{{ .Values.zabbixWebService.service.port }}/report"
            - name: ZBX_STARTREPORTWRITERS
              value: {{ .Values.zabbixWebService.replicaCount | quote }}
            - name: ZBX_JAVAGATEWAY_ENABLE
              value: {{ .Values.zabbixJavaGateway.enabled | quote }}
            - name: ZBX_JAVAGATEWAY
              value: {{ template "zabbix.fullname" . }}-{{ .Values.zabbixJavaGateway.ZBX_JAVAGATEWAY }}
            - name: ZBX_JAVAGATEWAYPORT
              value: {{ .Values.zabbixJavaGateway.service.port | quote }}
            - name: ZBX_STARTJAVAPOLLERS
              value: {{ .Values.zabbixJavaGateway.ZBX_STARTJAVAPOLLERS | quote }}
            {{- end }}
            {{- if .Values.zabbixBrowserMonitoring.enabled }}
            - name: ZBX_STARTBROWSERPOLLERS
              value: {{ .Values.zabbixBrowserMonitoring.pollers | quote }}
            {{- end }}
            {{- if .Values.zabbixBrowserMonitoring.customWebDriverURL }}
            - name: ZBX_WEBDRIVERURL
              value: {{ .Values.zabbixBrowserMonitoring.customWebDriverURL | quote }}
            {{- else }}
            - name: ZBX_WEBDRIVERURL
              value: http://{{ template "zabbix.fullname" . }}-{{ .Values.zabbixBrowserMonitoring.webdriver.name }}:{{ .Values.zabbixBrowserMonitoring.webdriver.port }}
            {{- end }}
          {{- with .Values.zabbixServer.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if and .Values.zabbixAgent.enabled .Values.zabbixAgent.runAsSidecar }}
        {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
        - name: ha-labels-sidecar
          resources:
            {{- toYaml .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.securityContext | nindent 12 }}
          image: "{{ .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.image.repository }}:{{ .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.image.tag }}"
          imagePullPolicy: {{ .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.image.pullPolicy }}
          env:
            {{- with .Values.zabbixServer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: LABEL_NAME
              value: {{ .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.labelName }}
          {{- with .Values.zabbixServer.zabbixServerHA.haLabelsSidecar.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: zabbix-agent
          resources:
            {{- toYaml .Values.zabbixAgent.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.zabbixAgent.securityContext | nindent 12 }}
          {{- if .Values.zabbixAgent.image.tag }}
          image: "{{ .Values.zabbixAgent.image.repository }}:{{ .Values.zabbixAgent.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixAgent.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zabbixAgent.image.pullPolicy }}
          env:
            - name: ZBX_HOSTNAME
              value: "Zabbix server"
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbixAgent.ZBX_SERVER_HOST | quote }}
            - name: ZBX_SERVER_PORT
              value: {{ .Values.zabbixAgent.ZBX_SERVER_PORT | quote }}
            - name: ZBX_PASSIVE_ALLOW
              value: {{ .Values.zabbixAgent.ZBX_PASSIVE_ALLOW | quote }}
            - name: ZBX_PASSIVESERVERS
              value: {{ .Values.zabbixAgent.ZBX_PASSIVESERVERS | quote }}
            - name: ZBX_ACTIVE_ALLOW
              value: {{ .Values.zabbixAgent.ZBX_ACTIVE_ALLOW | quote }}
            - name: ZBX_ACTIVESERVERS
              value: {{ .Values.zabbixAgent.ZBX_ACTIVESERVERS | quote }}
            - name: ZBX_DEBUGLEVEL
              value: {{ .Values.zabbixAgent.ZBX_DEBUGLEVEL | quote }}
            - name: ZBX_TIMEOUT
              value: {{ .Values.zabbixAgent.ZBX_TIMEOUT | quote }}
            - name: ZBX_LOADMODULE
              value: {{ .Values.zabbixAgent.ZBX_LOADMODULE }}
            {{- with .Values.zabbixAgent.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: zabbix-agent
              containerPort: 10050
              protocol: TCP
          {{- with .Values.zabbixAgent.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixAgent.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixAgent.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixAgent.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.zabbixServer.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixServer.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- range .Values.zabbixAgent.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      volumes:
      {{- if .Values.zabbixServer.zabbixServerHA.enabled }}
        - name: init-waitschema-script
          configMap:
            name: {{ template "zabbix.fullname" . }}-waitdbschema-script
      {{- end }}
      {{- with .Values.zabbixServer.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zabbixAgent.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
